spring:
  boot:
    admin:
      client:
        url: http://localhost:1111
        username: admin
        password: 123
        instance:
          prefer-ip: true
          metadata:
            management:
              port: 8081
            user:
              name: actuator
              password: 123
  application:
    name: Api Notifications
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/country?createDatabaseIfNotExist=true&serverTimezone=UTC
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  profiles:
    active: 
      - dev
      - jpa

integracao:
  api:
    localidades:
      url: 'http://localhost:3000'
      paises-path: '/paises'

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "metrics, health, info, audievents, usuarios, loggers"
    jmx:
      exposure:
        include: "metrics"
  metrics:
    enable:
      executor: false
  health:
    diskspace:
      enabled: false
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
      roles: 'ACTUATOR'
    metrics:
      enabled: true
    info:
      enabled: true
    auditevents:
      enabled: true
    loggers:
      enabled: true

info:
  application:
    nome: ${spring.application.name}
    descricao: Api Notifications
